[package]
name = "dog-detector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camera_capture = "0.5.0"
image = "0.24.1"
tract-onnx = "0.17.4"
tract-tensorflow = "0.17.4"
